theme: jekyll-theme-slate

# Site settings
title: ![zelos](./images/zelos.png) Zelos Technology
email: contact@zelostech.com
description: Pioneers in Autonomous Driving with leading Technologies
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://zelostech.com" # the base hostname & protocol for your site
